In [1]:
import numpy as np
import pandas as pd

버전 확인

In [2]:
#python
import sys
print(sys.version)

!python --version

3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0]
Python 3.8.10


In [3]:
# numpy
np.__version__

'1.21.6'

In [4]:
#pandas
pd.__version__

'1.3.5'

In [6]:
# 구글 colab
# !pip freeze

numpy datatype... 다 못적었음







In [7]:
from google.colab import drive
drive.mount('/content/drive')

%cd /content/drive/MyDrive/dataanalysis

Mounted at /content/drive
/content/drive/MyDrive/dataanalysis


###파일 형식 데이터 불러오기

In [9]:
# 읽어오는 파일에 컬러며이 없으면 header = None을 설정한다.
# 그렇지 않으면 첫번째 줄을 컬럼명으로 인식을 하기 때문이다.
# header 파라미터의 default:'infer'
data = pd.read_csv('./pdsample/num.txt', header = None)
data

# 행 이름,, 열 이름 등이 붙는다.

0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10

In [10]:
type(data) # 데이터 프레임

pandas.core.frame.DataFrame

In [11]:
# 컬럼(열)
print(data[0]) # 0번째 열의 데이터
print(type(data[0])) # 시리즈

0    1
1    6
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>


In [12]:
# index(행)
print(data.iloc[0]) # 행으로 가져오겠다 싶으면 iloc로 가져오면 된다. 
print(type(data.iloc[0])) #series

0    1
1    2
2    3
3    4
4    5
Name: 0, dtype: int64
<class 'pandas.core.series.Series'>


In [15]:
#numpy 참고
a = np.arange(12).reshape(3,4)
print(a)
print(a[1][2]) # 1번째 행 2번째 열
print(a[1])
print(a[1,2:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
6
[4 5 6 7]
[6 7]


In [17]:
# python list 참고
b=[[0,1,2,3],[4,5,6,7],[8,9,10,11]]
print(b[1][2])
print(b[1])
# print(b[1,2:]) # list에서는 슬라이싱 안됨

6
[4, 5, 6, 7]


In [18]:
# .values하면 numpy 포맷으로 변환한다.
# 내부적으로 numpy로 되어 있기 때문에 가능하다.
print(data.values)
print(type(data.values)) # 배열로 되어 있다.
data.values

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
<class 'numpy.ndarray'>


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [20]:
#__array__가 있으면 numpy와 호환된다.
# dir(data)

### 웹 주소에서 데이터 불러오기

In [33]:
# header은 기본이 첫줄을 컬럼며으로 가져오도록 설정이 되어 있기 때문에 header ='infer' 생략 가능하다.
data = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv', header='infer')
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [34]:
# 전반적인 데이터 정보 확인
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object 
 3   smoker      244 non-null    object 
 4   day         244 non-null    object 
 5   time        244 non-null    object 
 6   size        244 non-null    int64  
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [35]:
# 기본적으로 앞의 5개를 보여줌
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [36]:
# 마지막 5개 보여줌
data.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [37]:
# random으로 1개씩 보여줌
data.sample()

total_bill  tip   sex smoker  day    time  size
184       40.55  3.0  Male    Yes  Sun  Dinner     2

In [38]:
# 보여줄 갯수를 지정할 수 있음
# data.head(10)
# data.tail(10)
data.sample(10)

total_bill   tip     sex smoker   day    time  size
135        8.51  1.25  Female     No  Thur   Lunch     2
106       20.49  4.06    Male    Yes   Sat  Dinner     2
226       10.09  2.00  Female    Yes   Fri   Lunch     2
37        16.93  3.07  Female     No   Sat  Dinner     3
236       12.60  1.00    Male    Yes   Sat  Dinner     2
91        22.49  3.50    Male     No   Fri  Dinner     2
184       40.55  3.00    Male    Yes   Sun  Dinner     2
65        20.08  3.15    Male     No   Sat  Dinner     3
94        22.75  3.25  Female     No   Fri  Dinner     2
70        12.02  1.97    Male     No   Sat  Dinner     2

In [39]:
# 데이터만 가져옴
data.values

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [40]:
data.index #  인덱스값 확인

RangeIndex(start=0, stop=244, step=1)

In [41]:
data.columns # 컬럼값 확인

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [46]:
# dict 타입
dictdata = {'name' : '홍길동', 'age':'30'}
# dictdata.name # 오류 발생.. 자바 스크립트에서
dictdata['name']
# dictdata['age']

'홍길동'

In [47]:
dir(dict)
dict.items # 메소드는 가로로 안나온다고?? 설명 못들음

<method 'items' of 'dict' objects>

In [48]:
# apndas는 dictionay와 attribute 방식 모두 가져올 수 있다. dic -> dictdata['name'], atr -> dictdata.name 방식임
# dictionary 방식 이용
data['tip'] # -> tip열에 있는 것이 모두 출력된다.
data['tip'][2] # 판다스에서는 행이 아니라 열이 들어간다. 열/행 이렇게 들어간다. , tip열의 2의 행에 있는 값을 가지고 온다.

3.5

In [55]:
# attribute 방식 이용
data.tip
# data.tip[2]

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [63]:
# data.iloc[0] # 행, 어느 컬럼명에는 어떤 값이 들어 있는지 출력
# data['tip']  # 열, 열에 있는 값을 출력,, 인덱스 값도 출력된다. 
# data[[0]] # 오류 발생. 왜? -> 

KeyError: ignored

In [58]:
# keyError
# 컬럼을 fancying indexing을 이용해서 가져올 때 index를 이용해서 가져올 수 있다.
# data[[0,2]]
data[['tip','day']] 

tip   day
0    1.01   Sun
1    1.66   Sun
2    3.50   Sun
3    3.31   Sun
4    3.61   Sun
..    ...   ...
239  5.92   Sat
240  2.00   Sat
241  2.00   Sat
242  1.75   Sat
243  3.00  Thur

[244 rows x 2 columns]

In [65]:
# TypeError 발생
# 컬럼을 slicing을 이용해서 가져올 수 없다.
# data['tip':'day']

# row를 slicing을 이용해서 가져올때는 index을 이용해서 가져온다.

data[1:3]

total_bill   tip   sex smoker  day    time  size
1       10.34  1.66  Male     No  Sun  Dinner     3
2       21.01  3.50  Male     No  Sun  Dinner     3

In [67]:
#KeyError
#data[3]

data.iloc[3] #indexing, 특정 인덱스에 있는 값을 가지고 온다.

total_bill     23.68
tip             3.31
sex             Male
smoker            No
day              Sun
time          Dinner
size               2
Name: 3, dtype: object

하나의 컬럼 또는 행 가져오면 Series로 리턴한다.  
fancy indexing을 이용해서 하나의 컬럼 또는 행을 가져오면 DataFrame으로 리턴한다.  

In [68]:
type(data.iloc[3])

pandas.core.series.Series

In [70]:
type(data['tip']) #Series
# type(data.tip) #Series

pandas.core.series.Series

In [72]:
type(data[['tip']]) # DataFrame

pandas.core.frame.DataFrame

In [85]:
# data.iloc[0:5]
data.iloc[0:5, 0:7]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [74]:
data.iloc[[0,3,5]] # fancy indxing data[['tip'.'smoker','day]]

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
3       23.68  3.31    Male     No  Sun  Dinner     2
5       25.29  4.71    Male     No  Sun  Dinner     4

In [80]:
# 3행 1열,, 배열처럼 접근할때
data.iloc[3][1] #list: a[3][1] #array : a[3,1]      # array : a[3,1]

3.31

In [81]:
data.iloc[0:2, 1:4]

tip     sex smoker
0  1.01  Female     No
1  1.66    Male     No

In [90]:
k = [[1,2,3],[4,5,6]]
print(type(k))
print(k[1][2])

<class 'list'>
6


In [92]:
m = np.array(k)
print(type(m)) # 배열
print(m[1,2]) 
print(k[1][2]) # 리스트는 배열처럼 사용이 안된다.

<class 'numpy.ndarray'>
6
6


In [95]:
s = pd.DataFrame(k)
print(type(s)) # .DataFrame
print(s[0][1]) # 4
print(s.iloc[0,1]) # 2         iloc는 0행 1열을 가지고 온다.
print(s.iloc[0][1]) # 2        이렇게 출력해도 이상이 없다. 

<class 'pandas.core.frame.DataFrame'>
4
2
2


In [96]:
data.iloc[0:3, 1:4] # 슬라이싱 사용 가능

tip     sex smoker
0  1.01  Female     No
1  1.66    Male     No
2  3.50    Male     No

In [97]:
# TypeErro
# 컬럼을 기준으로 슬라이싱은 안된다.
# data['tip':'sex'] # 열은 슬라이싱 안됨

In [98]:
data.iloc[[0,3,5], [1,4,5]] #iloc[[행],[열]] # 슬라이싱도 가능하고 인덱싱도 가능하고 iloc는 배열의 접근 방식을 그대로 사용할 수 있다고 생각하면 된다.

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

iloc는 indexer을 이용해서 가져오고, loc를 이름을 이용해서 가져온다.

In [100]:
# 행은 이름이 설정되어 있지 않아서 자동으로 생성된 Range Index가 이름이 도니다.
data.loc[0,'tip']

1.01

In [102]:
data.loc[0:5, 'tip':'time'] # 슬라이싱이 가능하다.

tip     sex smoker  day    time
0  1.01  Female     No  Sun  Dinner
1  1.66    Male     No  Sun  Dinner
2  3.50    Male     No  Sun  Dinner
3  3.31    Male     No  Sun  Dinner
4  3.61  Female     No  Sun  Dinner
5  4.71    Male     No  Sun  Dinner

In [103]:
# 펜싱 인덱싱도 가능하다.
data.loc[[0,3,5],['tip','day','time']]

tip  day    time
0  1.01  Sun  Dinner
3  3.31  Sun  Dinner
5  4.71  Sun  Dinner

### at
이름으로 한 위치의 값만 가져온

In [115]:
# data.at[0,'tip']    # ok
# data.loc[0,'tip']   # ok
# data.iloc[0,1]      # ok
# data.at[0]['tip']   #TypeError
# data.loc[0]['tip']  # ok
# data.iloc[0]['tip'] # ok
data['tip'] # 열 지정. 하나만 적어준다.
data[3:5]    # 행 지정. n번에 있는 것을 가지고 와라,, 범위 지정 가능(슬라이싱 이용)


total_bill   tip     sex smoker  day    time  size
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [116]:
data

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [117]:
# at은 slicing을 사용할 수 없다.
# data.at[0:3,'tip'] # 슬라이싱을 사용할 수 없다.

In [119]:
# at은 fancying indexing을 사용할 수 없다.
data.at[[1,3,5],['tip','smoker','day']]

TypeError: ignored

In [137]:
# data['tip','sex'] # 인덱싱 방법으로 못가지고 온다.
# data[['tip','sex']] # 이렇게는 가지고 올 수 있다.

# iloc는 슬라이싱, 해싱 인덱싱을 사용할 수 있다.

data.iloc[:,1] # 인덱스를 이용해 가지고 온다, 1열에 있는 값을 가지고 온다.
data.iloc[:,[1,2]] # 펜싱 기법이여서 [[안에 :을 사용하지 못한다.]], 떨어져 있는 경우 이 방법을 사용한다.
data.iloc[:,1:3] 
data.loc[:,'tip':'sex'] # 이름을 잉요해서 가지고 올 수 있다. 떨어져 있으면 이 방법을 사용하지 못한다.
data.iloc[0,1] # 특정 위치에 있는 값을 가지고 온다.

# iloc loc 차이점은 이름 또는 인덱스를 가지고 와야하느것, 지정할때 행이 먼저 오고 그 담에 열이 오고.
# at은 특정 위치에 있는 것을 가지고 와야 하기 때문에 행렬을 가지고 오지만, 이름으로 가지고 와서 하나씩만 가지고 온다?
# 데이터 프레임을 가지고 올 때, 행 또는 열, 하나씩만 가지고 올 수 있다.
# data[열] # 열 하나만 지정
# data[행:행] # 행의 범위를 지정
# data[['tip','day']] #ok
# data['tip':'day']   #TypeError   # 슬라이싱 사용시 오류 발생. 슬라이싱은 행일때만 사용한다.

1.01

###iat
iat은 인덱스 번호로 한 위치의 값을 가져온디.

In [138]:
data.iat[0,1]
#data.at[0,'tip']

1.01

In [139]:
#iat은 슬라이싱을 사용할 수 없다.
data.iat[0:3,1]

ValueError: ignored

### boolean indexing

In [141]:
# data.tip >= 5
data['tip'] >= 5 # tip이 열에 있는 값이 5보다 크거나 같으면 true로 적어라

0      False
1      False
2      False
3      False
4      False
       ...  
239     True
240    False
241    False
242    False
243    False
Name: tip, Length: 244, dtype: bool

In [142]:
data[data['tip']>=5] #data[True,False,True,Ture...] 값이 true인 것만 가지고 온다.

total_bill    tip     sex smoker   day    time  size
11        35.26   5.00  Female     No   Sun  Dinner     4
23        39.42   7.58    Male     No   Sat  Dinner     4
39        31.27   5.00    Male     No   Sat  Dinner     3
44        30.40   5.60    Male     No   Sun  Dinner     4
46        22.23   5.00    Male     No   Sun  Dinner     2
47        32.40   6.00    Male     No   Sun  Dinner     4
52        34.81   5.20  Female     No   Sun  Dinner     4
59        48.27   6.73    Male     No   Sat  Dinner     4
73        25.28   5.00  Female    Yes   Sat  Dinner     2
83        32.68   5.00    Male    Yes  Thur   Lunch     2
85        34.83   5.17  Female     No  Thur   Lunch     4
88        24.71   5.85    Male     No  Thur   Lunch     2
116       29.93   5.07    Male     No   Sun  Dinner     4
141       34.30   6.70    Male     No  Thur   Lunch     6
142       41.19   5.00    Male     No  Thur   Lunch     5
143       27.05   5.00  Female     No  Thur   Lunch     6
155       29.85   5.14  Female     No   Sun  Dinner     5
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
172        7.25   5.15    Male    Yes   Sun  Dinner     2
181       23.33   5.65    Male    Yes   Sun  Dinner     2
183       23.17   6.50    Male    Yes   Sun  Dinner     4
185       20.69   5.00    Male     No   Sun  Dinner     5
197       43.11   5.00  Female    Yes  Thur   Lunch     4
211       25.89   5.16    Male    Yes   Sat  Dinner     4
212       48.33   9.00    Male     No   Sat  Dinner     4
214       28.17   6.50  Female    Yes   Sat  Dinner     3
239       29.03   5.92    Male     No   Sat  Dinner     3

In [151]:
data.tip
data['tip']
a=data[data['tip']>=5]  # 이 조건을 만족하는 모든 행을 가지고 온다.

# print(a.head)
# print(type(a))
# a['tip']

# 데이터 프레임   //
# data[data['tip']>=5]['tip'] # data[data['tip']>=5]의 결과는 DataFrame
#data['tip'][3]             # data['tip']의 결과는 Series

print(type(data.iloc[3]))
 # 3행에 있는 값을 가지고 온다. 열의 이름을 출력한다.
print(type(data['tip'])) #<class 'pandas.core.series.Series'>

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>


In [153]:
a=[[1,2,3,4,5],[6,7,8,9,10]]
a

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [166]:
a[0][3] # 4
type(a[0:2]) # list 0번째 행부터 2미만에서 .. 리스트를 가지고 온다.
a[0:2][3:4] # [] 
a[0:2][0:1] # [[1, 2, 3, 4, 5]] 값을 출력하기 위해서 가지고 온 범위 내로 적어줘야 한다. 
# a[0,3] # 리스트이기 떄문에 배열 형태로는 가지고 오지 못한다.TypeError    
# a[[0,1][2,4]] # 리스트일때 오류가 발생한다. TypeError    
# a[[0,1]] #TypeError

[[1, 2, 3, 4, 5]]

In [175]:
b=np.array(a)
type(b) #ndarray
b[0,3]
b[0][3]
b[0:1,2:4] # 0번째부터 1번째 미만 행에서 2번째, 4미만 열의 값을 가지고 오라. array([[3, 4]])
b[0:1][2:4] # b[0:1]의 결과값에서 [2:4]를 가지고 오라... 값이 없어서 안 가지고 온다.

b[[0,1],[2,4]] #b[0,3]와 같은 의미

array([ 3, 10])

In [176]:
data[data['tip']>=5].loc[:,'tip':'day']

tip     sex smoker   day
11    5.00  Female     No   Sun
23    7.58    Male     No   Sat
39    5.00    Male     No   Sat
44    5.60    Male     No   Sun
46    5.00    Male     No   Sun
47    6.00    Male     No   Sun
52    5.20  Female     No   Sun
59    6.73    Male     No   Sat
73    5.00  Female    Yes   Sat
83    5.00    Male    Yes  Thur
85    5.17  Female     No  Thur
88    5.85    Male     No  Thur
116   5.07    Male     No   Sun
141   6.70    Male     No  Thur
142   5.00    Male     No  Thur
143   5.00  Female     No  Thur
155   5.14  Female     No   Sun
156   5.00    Male     No   Sun
170  10.00    Male    Yes   Sat
172   5.15    Male    Yes   Sun
181   5.65    Male    Yes   Sun
183   6.50    Male    Yes   Sun
185   5.00    Male     No   Sun
197   5.00  Female    Yes  Thur
211   5.16    Male    Yes   Sat
212   9.00    Male     No   Sat
214   6.50  Female    Yes   Sat
239   5.92    Male     No   Sat

In [187]:
data[data['tip']>=5].loc[:,'tip':'day']
data[data['tip'] >=5] # 조건이 true 인것만 가지고 온다.
a=data.tail(6).copy()
print(a)
# a[[False, True, False, False,False]] # 수행한 값 중에 true인 값만 가지고 올ㄸ
a[a['tip']>=5] #행에 있는 값만 다 가지고 온다.

     total_bill   tip     sex smoker   day    time  size
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2


total_bill   tip   sex smoker  day    time  size
239       29.03  5.92  Male     No  Sat  Dinner     3

In [190]:
data[data['tip']>=5].iloc[:,1:5]

tip     sex smoker   day
11    5.00  Female     No   Sun
23    7.58    Male     No   Sat
39    5.00    Male     No   Sat
44    5.60    Male     No   Sun
46    5.00    Male     No   Sun
47    6.00    Male     No   Sun
52    5.20  Female     No   Sun
59    6.73    Male     No   Sat
73    5.00  Female    Yes   Sat
83    5.00    Male    Yes  Thur
85    5.17  Female     No  Thur
88    5.85    Male     No  Thur
116   5.07    Male     No   Sun
141   6.70    Male     No  Thur
142   5.00    Male     No  Thur
143   5.00  Female     No  Thur
155   5.14  Female     No   Sun
156   5.00    Male     No   Sun
170  10.00    Male    Yes   Sat
172   5.15    Male    Yes   Sun
181   5.65    Male    Yes   Sun
183   6.50    Male    Yes   Sun
185   5.00    Male     No   Sun
197   5.00  Female    Yes  Thur
211   5.16    Male    Yes   Sat
212   9.00    Male     No   Sat
214   6.50  Female    Yes   Sat
239   5.92    Male     No   Sat

In [193]:
data[data['tip']>=5][['tip','day']] # 해싱 인덱싱을 사용하는건가??

tip   day
11    5.00   Sun
23    7.58   Sat
39    5.00   Sat
44    5.60   Sun
46    5.00   Sun
47    6.00   Sun
52    5.20   Sun
59    6.73   Sat
73    5.00   Sat
83    5.00  Thur
85    5.17  Thur
88    5.85  Thur
116   5.07   Sun
141   6.70  Thur
142   5.00  Thur
143   5.00  Thur
155   5.14   Sun
156   5.00   Sun
170  10.00   Sat
172   5.15   Sun
181   5.65   Sun
183   6.50   Sun
185   5.00   Sun
197   5.00  Thur
211   5.16   Sat
212   9.00   Sat
214   6.50   Sat
239   5.92   Sat

### 요일이 'Sun'이거나 'Sat'의 tip과 day 가져오기

In [201]:
data[(data['day']=='Sun')| (data['day']=='Sat')][['tip','day']]

a = data[(data['day']=='Sun')|(data['day']=='Sat')]

a['day'].unique()
a[['tip','day']]

tip  day
0    1.01  Sun
1    1.66  Sun
2    3.50  Sun
3    3.31  Sun
4    3.61  Sun
..    ...  ...
238  4.67  Sat
239  5.92  Sat
240  2.00  Sat
241  2.00  Sat
242  1.75  Sat

[163 rows x 2 columns]

In [214]:
# 참고
# len([1,2,3])
# len('123')
# len({'a':1,'b':2,'c':3})
# len(data) # tips : 244

# [1,2,3].size                    #AttributeError
# '123'.size                      #AttributeError
# {'a':1,'b':2,'c':3}.size        #AttributeError

import numpy as np
# (np.array([1,2,3])).size    # 3 
# data.size  # 244 * 7
# data['tip'].size  # 244
# data.tip


# print(dir(list())) # 사이즈를 제공하지 않는다.
# print(dir(str()))  # 사이즈를 제공하지 않는다.
# print(dir(dict())) # 사이즈를 제공하지 않는다.
# print(dir(pd.DataFrame([]))) # 사이즈를 제공한다.
print(dir(pd.Series())) # 사이즈를 제공한다.


['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_REVERSED', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__long__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__nonzero__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__'

<ipython-input-214-1f882bafbfa8>:22: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  print(dir(pd.Series())) # 사이즈를 제공한다.


In [216]:
data.columns # 사이즈 있다.

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [220]:
data.size # attribute 방식으로 사용 못한다.
data['size']
# data.tip

0      2
1      3
2      3
3      2
4      4
      ..
239    3
240    2
241    2
242    2
243    2
Name: size, Length: 244, dtype: int64

In [221]:
# 컬럼명을 바꿀때 mapper, colums 옵션을 이용해서 변경할 수 있다.
data2 = data.rename(mapper={'size' :'size_'},axis=1) # 행 또는 열을 바꾸 수 있음. axis가 0이면 행, 1이면 열이 바뀐다.
data2 = data.rename(columns={'size' :'size_'})
data2

total_bill   tip     sex smoker   day    time  size_
0         16.99  1.01  Female     No   Sun  Dinner      2
1         10.34  1.66    Male     No   Sun  Dinner      3
2         21.01  3.50    Male     No   Sun  Dinner      3
3         23.68  3.31    Male     No   Sun  Dinner      2
4         24.59  3.61  Female     No   Sun  Dinner      4
..          ...   ...     ...    ...   ...     ...    ...
239       29.03  5.92    Male     No   Sat  Dinner      3
240       27.18  2.00  Female    Yes   Sat  Dinner      2
241       22.67  2.00    Male    Yes   Sat  Dinner      2
242       17.82  1.75    Male     No   Sat  Dinner      2
243       18.78  3.00  Female     No  Thur  Dinner      2

[244 rows x 7 columns]

In [222]:
type(data['sex'])

pandas.core.series.Series

In [223]:
print(data['sex'].dtype)

object


In [224]:
#object을 category로 데이터 타입으로 변경한다.
data['sex']=data['sex'].astype('category')

In [225]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    object  
 4   day         244 non-null    object  
 5   time        244 non-null    object  
 6   size        244 non-null    int64   
dtypes: category(1), float64(2), int64(1), object(3)
memory usage: 11.9+ KB


In [226]:
data.sample()

total_bill   tip     sex smoker  day    time  size
229       22.12  2.88  Female    Yes  Sat  Dinner     2

In [227]:
#data에서 Female만 가져오기
#data[data['sex']=='Female']
data[data.sex=='Female']

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
..          ...   ...     ...    ...   ...     ...   ...
226       10.09  2.00  Female    Yes   Fri   Lunch     2
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[87 rows x 7 columns]

In [229]:
# data[data['sex']=='Female']['sex'].unique()
data[data.sex=='Female']['sex'].unique()

['Female']
Categories (2, object): ['Female', 'Male']

### 금요일에 온 여자만 가져오기

In [230]:
data['day'].unique()
# dictionary 방식
data[(data['day']=='Fri')&(data['sex']=='Female')]
#agttibute 방식
data[(data.day=='Fri')&(data.sex=='Female')]

total_bill   tip     sex smoker  day    time  size
92         5.75  1.00  Female    Yes  Fri  Dinner     2
93        16.32  4.30  Female    Yes  Fri  Dinner     2
94        22.75  3.25  Female     No  Fri  Dinner     2
100       11.35  2.50  Female    Yes  Fri  Dinner     2
101       15.38  3.00  Female    Yes  Fri  Dinner     2
221       13.42  3.48  Female    Yes  Fri   Lunch     2
223       15.98  3.00  Female     No  Fri   Lunch     3
225       16.27  2.50  Female    Yes  Fri   Lunch     2
226       10.09  2.00  Female    Yes  Fri   Lunch     2

In [233]:
data[(data['day']=='Fri')&(data['sex']=='Female')]['sex'].unique() # Female

data[(data.day=='Fri') &(data.sex=='Female')]['day'].unique()      # Fri

array(['Fri'], dtype=object)

### describe
- describe는 기초적인 통계 분석을 해준다

In [234]:
# describe()의 기본은 데이터가 숫자로 된 컬럼만 가져온다.
data.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [235]:
type(data.describe()) #DataFrame

pandas.core.frame.DataFrame

In [236]:
# pandas는 numpy 기반이라서 numpy 기능을 사용할 수 있다.
data.describe().T

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [237]:
# describe()은 기본적으로 숫자형 데이터만 분석한다.
# include 옵션을 사용하면 다른 분석할 데이터 타입을 지정할 수 있다.
data.describe(include=['object'])
data.describe(include=['float64','object'])

total_bill         tip smoker  day    time
count   244.000000  244.000000    244  244     244
unique         NaN         NaN      2    4       2
top            NaN         NaN     No  Sat  Dinner
freq           NaN         NaN    151   87     176
mean     19.785943    2.998279    NaN  NaN     NaN
std       8.902412    1.383638    NaN  NaN     NaN
min       3.070000    1.000000    NaN  NaN     NaN
25%      13.347500    2.000000    NaN  NaN     NaN
50%      17.795000    2.900000    NaN  NaN     NaN
75%      24.127500    3.562500    NaN  NaN     NaN
max      50.810000   10.000000    NaN  NaN     NaN

In [240]:
# 데이터 타입이 object일때만 가져온다.
# data.describe(include=['object'])
data.describe(include='O') # 대문자 알파벳 0

smoker  day    time
count     244  244     244
unique      2    4       2
top        No  Sat  Dinner
freq      151   87     176

In [241]:
np.number

numpy.number

In [242]:
data.describe(include=['float64'])
data.describe(include=np.number)

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [243]:
# 모든 타입의 데이터를 분석할때는 include='all'로 설정한다.
data.describe(include='all')

total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [244]:
#day 컬럼의 요소갯수 244개
data['day'].values.size

244

In [245]:
#value_count()는 unique한 값과 그 개수를 알려준다.(Series만 사용한다.)
data['day'].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64